# Generated by Django 6.0.7 on 2026-07-30 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='barbeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='profissionais.barbeiro'),
        ),
    ]
