# Generated by Django 6.0.7 on 2026-07-30 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissionais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barbeiro',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_barbeiro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horariotrabalho',
            name='barbeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabalho', to='profissionais.barbeiro'),
        ),
        migrations.AlterUniqueTogether(
            name='horariotrabalho',
            unique_together={('barbeiro', 'dia_semana', 'hora_inicio')},
        ),
    ]
